name: Build and Deploy - DEV

on:
  push:
    branches:
      - main

  workflow_dispatch:

# Environment variables available to all jobs and steps in workflow
env:
  PROVISIONER_APP_ID: fff-provisioner-apps
  SERVICE_NAME: ${{ github.event.repository.name }}
  RUN_REGION: us-west1-c
  PROJECT_ID: dev-resources-257716
  COMMIT_SHA: ${{ github.sha }}


jobs:
  setup-build-dev:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      # Get the code
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Deploy app
        uses: victorargento/pm2-deployment@main
        with:
          remote-path: "/deployment/api"
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 2080
          password: ${{ secrets.PASSWORD }}
          pm2-id: "api"
          script: |
            cd /backend-project-folder
            sudo git stash
            sudo GIT_SSH_COMMAND="ssh -i ~/.ssh/authorized_keys" git pull origin dev
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm install
            pm2 restart 0
